title: "Dynamic config application"
server:
  bind: ":8080"
logger:
  level: "debug"
postgres:
  host: "postgres_container"
  port: "5432"
  user: "root"
  password: "root"
  dbname: "postgres_db"
  sslmode: "disable"